# -*- coding: utf-8 -*-
"""notebook_06.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RtiBdL0lEGFNnWQBiOAZYlYmGMO8Kd2x

<a href="https://colab.research.google.com/github/caretkwon/yonsei_tinybible/blob/260622_01/notebook_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Notebook 6 — Toward a Tiny GPT

이제 남은 모듈들을 하나씩 추가하여 **좀 더 GPT다운 구조**로 갑니다.

이번 노트북에서 추가하는 것들:

- multi-head attention
- feedforward network
- residual connection
- layer normalization
- block stacking
"""
# python

import subprocess
subprocess.run(["wget", "-q", "https://www.gutenberg.org/files/10/10-0.txt", "-O", "input.txt"], check=True)

import csv
import json
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from pathlib import Path

# Ensure input.txt exists and is not empty
input_file_path = Path("input.txt")

# If the file doesn't exist or is empty, try downloading it
if not input_file_path.exists() or input_file_path.stat().st_size == 0:
    print("Downloading King James Bible...")
    # Remove existing file to ensure a fresh download in case of corruption
    if input_file_path.exists():
        input_file_path.unlink()
    # !wget -q https://www.gutenberg.org/files/10/10-0.txt -O input.txt

text = open("input.txt", "r", encoding="utf-8").read()

# Critical check: if text is still empty after download attempt and read
if not text:
    raise ValueError("Downloaded text file is empty. Please check the download URL or network connection.")

chars = sorted(list(set(text)))
stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for ch, i in stoi.items()}
vocab_size = len(chars)
data = torch.tensor([stoi[ch] for ch in text], dtype=torch.long)

class NextTokenDataset(Dataset):
    def __init__(self, data, block_size):
        self.data = data
        self.block_size = block_size

    def __len__(self):
        # Ensure that the dataset length is never negative
        return max(0, len(self.data) - self.block_size)

    def __getitem__(self, idx):
        x = self.data[idx : idx + self.block_size]
        y = self.data[idx + 1 : idx + self.block_size + 1]
        return x, y

block_size = 64

# Another critical check: Ensure data has enough length for block_size
# We need at least block_size + 1 elements for x and y to be non-empty and correctly shifted
if len(data) < block_size + 1:
    raise ValueError(
        f"Dataset is too small ({len(data)} characters) for the specified block_size ({block_size}). "
        "Please use a smaller block_size or ensure a larger text file is downloaded."
    )

dataset = NextTokenDataset(data, block_size)
loader = DataLoader(dataset, batch_size=64, shuffle=True)
xb, yb = next(iter(loader))

"""## 1. Multi-head attention"""

class Head(nn.Module):
    def __init__(self, emb_dim, head_size, block_size, dropout=0.1):
        super().__init__()
        self.key = nn.Linear(emb_dim, head_size, bias=False)
        self.query = nn.Linear(emb_dim, head_size, bias=False)
        self.value = nn.Linear(emb_dim, head_size, bias=False)
        self.register_buffer("tril", torch.tril(torch.ones(block_size, block_size)))
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B, T, C = x.shape
        k = self.key(x)
        q = self.query(x)
        v = self.value(x)
        wei = q @ k.transpose(-2, -1) * (k.size(-1) ** -0.5)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float("-inf"))
        wei = F.softmax(wei, dim=-1)
        wei = self.dropout(wei)
        out = wei @ v
        return out

class MultiHeadAttention(nn.Module):
    def __init__(self, emb_dim, num_heads, block_size, dropout=0.1):
        super().__init__()
        head_size = emb_dim // num_heads
        self.heads = nn.ModuleList([Head(emb_dim, head_size, block_size, dropout) for _ in range(num_heads)])
        self.proj = nn.Linear(emb_dim, emb_dim)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.proj(out)
        out = self.dropout(out)
        return out

"""## 2. Feedforward + Block"""

class FeedForward(nn.Module):
    def __init__(self, emb_dim, dropout=0.1):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(emb_dim, 4 * emb_dim),
            nn.ReLU(),
            nn.Linear(4 * emb_dim, emb_dim),
            nn.Dropout(dropout),
        )
    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    def __init__(self, emb_dim, num_heads, block_size, dropout=0.1):
        super().__init__()
        self.ln1 = nn.LayerNorm(emb_dim)
        self.sa = MultiHeadAttention(emb_dim, num_heads, block_size, dropout)
        self.ln2 = nn.LayerNorm(emb_dim)
        self.ffwd = FeedForward(emb_dim, dropout)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

"""## 3. Tiny GPT"""

class TinyGPT(nn.Module):
    def __init__(self, vocab_size, block_size, emb_dim=128, num_heads=4, num_layers=4, dropout=0.1):
        super().__init__()
        self.token_embedding = nn.Embedding(vocab_size, emb_dim)
        self.position_embedding = nn.Embedding(block_size, emb_dim)
        self.blocks = nn.Sequential(*[
            Block(emb_dim, num_heads, block_size, dropout) for _ in range(num_layers)
        ])
        self.ln_f = nn.LayerNorm(emb_dim)
        self.lm_head = nn.Linear(emb_dim, vocab_size)

    def forward(self, x):
        B, T = x.shape
        pos = torch.arange(T, device=x.device)
        tok = self.token_embedding(x)
        pos = self.position_embedding(pos)[None]
        h = tok + pos
        h = self.blocks(h)
        h = self.ln_f(h)
        logits = self.lm_head(h)
        return logits

model = TinyGPT(vocab_size, block_size)
logits = model(xb)
print("logits.shape:", logits.shape)

"""## 4. 학습"""

def sequence_cross_entropy(logits, targets):
    return F.cross_entropy(logits.transpose(1, 2), targets)

def train_one_epoch(model, loader, optimizer, device, max_steps=None):
    model.train()
    total_loss, total_count = 0.0, 0
    for step, (xb, yb) in enumerate(loader):
        xb, yb = xb.to(device), yb.to(device)
        logits = model(xb)
        loss = sequence_cross_entropy(logits, yb)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        total_loss += loss.item() * xb.size(0)
        total_count += xb.size(0)
        if max_steps is not None and step + 1 >= max_steps:
            break
    return total_loss / total_count


def save_training_history(history, csv_path, json_path):
    fieldnames = ["epoch", "train_loss"]
    with open(csv_path, "w", newline="", encoding="utf-8") as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(history)
    with open(json_path, "w", encoding="utf-8") as jsonfile:
        json.dump(history, jsonfile, indent=2, ensure_ascii=False)


def save_checkpoint(model, optimizer, epoch, loss, path):
    state = {
        "epoch": epoch,
        "model_state_dict": model.state_dict(),
        "optimizer_state_dict": optimizer.state_dict(),
        "train_loss": loss,
    }
    torch.save(state, path)


def load_checkpoint(model, optimizer, path, device):
    checkpoint = torch.load(path, map_location=device)
    model.load_state_dict(checkpoint["model_state_dict"])
    optimizer.load_state_dict(checkpoint["optimizer_state_dict"])
    return checkpoint["epoch"], checkpoint.get("train_loss", None)


def load_training_history(json_path):
    if Path(json_path).exists():
        with open(json_path, "r", encoding="utf-8") as jsonfile:
            try:
                return json.load(jsonfile)
            except json.JSONDecodeError:
                return []
    return []


device = "cuda" if torch.cuda.is_available() else "cpu"
model = TinyGPT(vocab_size, block_size).to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=3e-4)

training_history = []
checkpoint_path = "tinygpt_checkpoint.pt"
csv_path = "training_history.csv"
json_path = "training_history.json"
max_epochs = 10

if Path(checkpoint_path).exists():
    last_epoch, last_loss = load_checkpoint(model, optimizer, checkpoint_path, device)
    training_history = load_training_history(json_path)
    start_epoch = last_epoch + 1
    print(f"Loaded checkpoint from epoch {last_epoch} (loss={last_loss:.4f}).")
else:
    start_epoch = 0

if start_epoch >= max_epochs:
    print(f"Checkpoint already trained for {max_epochs} epochs. Skipping training.")
else:
    for epoch in range(start_epoch, max_epochs):
        train_loss = train_one_epoch(model, loader, optimizer, device, max_steps=300)
        training_history.append({"epoch": epoch, "train_loss": train_loss})
        print(f"epoch {epoch:2d} | train loss {train_loss:.4f}")
        save_checkpoint(model, optimizer, epoch, train_loss, checkpoint_path)
        save_training_history(training_history, csv_path, json_path)

"""## 5. Sampling"""

@torch.no_grad()
def sample_gpt(model, block_size, stoi, itos, device, start_text="ROMEO:", max_new_tokens=400):
    model.eval()
    context = torch.zeros((1, block_size), dtype=torch.long, device=device)
    for ch in start_text:
        if ch in stoi:
            ix = torch.tensor([[stoi[ch]]], device=device)
            context = torch.cat([context[:, 1:], ix], dim=1)
    out = list(start_text)
    for _ in range(max_new_tokens):
        logits = model(context)
        logits = logits[:, -1, :]
        probs = F.softmax(logits, dim=-1)
        ix = torch.multinomial(probs, num_samples=1)
        out.append(itos[ix.item()])
        context = torch.cat([context[:, 1:], ix], dim=1)
    return "".join(out)

print(sample_gpt(model, block_size, stoi, itos, device, start_text="15:57", max_new_tokens=500))

"""## 6. 정리

이제 아주 작은 GPT 구조가 완성되었습니다.

전체 흐름은 다음과 같습니다.

1. bigram
2. MLP on names
3. MLP on Shakespeare
4. GPT-style dataset + minimal sequence model
5. single-head masked self-attention
6. tiny GPT
"""

